# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/siqnole/Documents/code/bpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/siqnole/Documents/code/bpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/siqnole/Documents/code/bpp/CMakeFiles /home/siqnole/Documents/code/bpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/siqnole/Documents/code/bpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named discord-bot

# Build rule for target.
discord-bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 discord-bot
.PHONY : discord-bot

# fast build rule for target.
discord-bot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/build
.PHONY : discord-bot/fast

commands/quiet_moderation/antispam_command.o: commands/quiet_moderation/antispam_command.cpp.o
.PHONY : commands/quiet_moderation/antispam_command.o

# target to build an object file
commands/quiet_moderation/antispam_command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/antispam_command.cpp.o
.PHONY : commands/quiet_moderation/antispam_command.cpp.o

commands/quiet_moderation/antispam_command.i: commands/quiet_moderation/antispam_command.cpp.i
.PHONY : commands/quiet_moderation/antispam_command.i

# target to preprocess a source file
commands/quiet_moderation/antispam_command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/antispam_command.cpp.i
.PHONY : commands/quiet_moderation/antispam_command.cpp.i

commands/quiet_moderation/antispam_command.s: commands/quiet_moderation/antispam_command.cpp.s
.PHONY : commands/quiet_moderation/antispam_command.s

# target to generate assembly for a file
commands/quiet_moderation/antispam_command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/antispam_command.cpp.s
.PHONY : commands/quiet_moderation/antispam_command.cpp.s

commands/quiet_moderation/antispam_handler.o: commands/quiet_moderation/antispam_handler.cpp.o
.PHONY : commands/quiet_moderation/antispam_handler.o

# target to build an object file
commands/quiet_moderation/antispam_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/antispam_handler.cpp.o
.PHONY : commands/quiet_moderation/antispam_handler.cpp.o

commands/quiet_moderation/antispam_handler.i: commands/quiet_moderation/antispam_handler.cpp.i
.PHONY : commands/quiet_moderation/antispam_handler.i

# target to preprocess a source file
commands/quiet_moderation/antispam_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/antispam_handler.cpp.i
.PHONY : commands/quiet_moderation/antispam_handler.cpp.i

commands/quiet_moderation/antispam_handler.s: commands/quiet_moderation/antispam_handler.cpp.s
.PHONY : commands/quiet_moderation/antispam_handler.s

# target to generate assembly for a file
commands/quiet_moderation/antispam_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/antispam_handler.cpp.s
.PHONY : commands/quiet_moderation/antispam_handler.cpp.s

commands/quiet_moderation/text_filter_command.o: commands/quiet_moderation/text_filter_command.cpp.o
.PHONY : commands/quiet_moderation/text_filter_command.o

# target to build an object file
commands/quiet_moderation/text_filter_command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/text_filter_command.cpp.o
.PHONY : commands/quiet_moderation/text_filter_command.cpp.o

commands/quiet_moderation/text_filter_command.i: commands/quiet_moderation/text_filter_command.cpp.i
.PHONY : commands/quiet_moderation/text_filter_command.i

# target to preprocess a source file
commands/quiet_moderation/text_filter_command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/text_filter_command.cpp.i
.PHONY : commands/quiet_moderation/text_filter_command.cpp.i

commands/quiet_moderation/text_filter_command.s: commands/quiet_moderation/text_filter_command.cpp.s
.PHONY : commands/quiet_moderation/text_filter_command.s

# target to generate assembly for a file
commands/quiet_moderation/text_filter_command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/text_filter_command.cpp.s
.PHONY : commands/quiet_moderation/text_filter_command.cpp.s

commands/quiet_moderation/text_filter_handler.o: commands/quiet_moderation/text_filter_handler.cpp.o
.PHONY : commands/quiet_moderation/text_filter_handler.o

# target to build an object file
commands/quiet_moderation/text_filter_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/text_filter_handler.cpp.o
.PHONY : commands/quiet_moderation/text_filter_handler.cpp.o

commands/quiet_moderation/text_filter_handler.i: commands/quiet_moderation/text_filter_handler.cpp.i
.PHONY : commands/quiet_moderation/text_filter_handler.i

# target to preprocess a source file
commands/quiet_moderation/text_filter_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/text_filter_handler.cpp.i
.PHONY : commands/quiet_moderation/text_filter_handler.cpp.i

commands/quiet_moderation/text_filter_handler.s: commands/quiet_moderation/text_filter_handler.cpp.s
.PHONY : commands/quiet_moderation/text_filter_handler.s

# target to generate assembly for a file
commands/quiet_moderation/text_filter_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/commands/quiet_moderation/text_filter_handler.cpp.s
.PHONY : commands/quiet_moderation/text_filter_handler.cpp.s

database/core/connection_pool.o: database/core/connection_pool.cpp.o
.PHONY : database/core/connection_pool.o

# target to build an object file
database/core/connection_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/core/connection_pool.cpp.o
.PHONY : database/core/connection_pool.cpp.o

database/core/connection_pool.i: database/core/connection_pool.cpp.i
.PHONY : database/core/connection_pool.i

# target to preprocess a source file
database/core/connection_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/core/connection_pool.cpp.i
.PHONY : database/core/connection_pool.cpp.i

database/core/connection_pool.s: database/core/connection_pool.cpp.s
.PHONY : database/core/connection_pool.s

# target to generate assembly for a file
database/core/connection_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/core/connection_pool.cpp.s
.PHONY : database/core/connection_pool.cpp.s

database/core/database.o: database/core/database.cpp.o
.PHONY : database/core/database.o

# target to build an object file
database/core/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/core/database.cpp.o
.PHONY : database/core/database.cpp.o

database/core/database.i: database/core/database.cpp.i
.PHONY : database/core/database.i

# target to preprocess a source file
database/core/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/core/database.cpp.i
.PHONY : database/core/database.cpp.i

database/core/database.s: database/core/database.cpp.s
.PHONY : database/core/database.s

# target to generate assembly for a file
database/core/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/core/database.cpp.s
.PHONY : database/core/database.cpp.s

database/operations/community/bugreport_operations.o: database/operations/community/bugreport_operations.cpp.o
.PHONY : database/operations/community/bugreport_operations.o

# target to build an object file
database/operations/community/bugreport_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/bugreport_operations.cpp.o
.PHONY : database/operations/community/bugreport_operations.cpp.o

database/operations/community/bugreport_operations.i: database/operations/community/bugreport_operations.cpp.i
.PHONY : database/operations/community/bugreport_operations.i

# target to preprocess a source file
database/operations/community/bugreport_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/bugreport_operations.cpp.i
.PHONY : database/operations/community/bugreport_operations.cpp.i

database/operations/community/bugreport_operations.s: database/operations/community/bugreport_operations.cpp.s
.PHONY : database/operations/community/bugreport_operations.s

# target to generate assembly for a file
database/operations/community/bugreport_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/bugreport_operations.cpp.s
.PHONY : database/operations/community/bugreport_operations.cpp.s

database/operations/community/patch_operations.o: database/operations/community/patch_operations.cpp.o
.PHONY : database/operations/community/patch_operations.o

# target to build an object file
database/operations/community/patch_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/patch_operations.cpp.o
.PHONY : database/operations/community/patch_operations.cpp.o

database/operations/community/patch_operations.i: database/operations/community/patch_operations.cpp.i
.PHONY : database/operations/community/patch_operations.i

# target to preprocess a source file
database/operations/community/patch_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/patch_operations.cpp.i
.PHONY : database/operations/community/patch_operations.cpp.i

database/operations/community/patch_operations.s: database/operations/community/patch_operations.cpp.s
.PHONY : database/operations/community/patch_operations.s

# target to generate assembly for a file
database/operations/community/patch_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/patch_operations.cpp.s
.PHONY : database/operations/community/patch_operations.cpp.s

database/operations/community/suggestion_operations.o: database/operations/community/suggestion_operations.cpp.o
.PHONY : database/operations/community/suggestion_operations.o

# target to build an object file
database/operations/community/suggestion_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/suggestion_operations.cpp.o
.PHONY : database/operations/community/suggestion_operations.cpp.o

database/operations/community/suggestion_operations.i: database/operations/community/suggestion_operations.cpp.i
.PHONY : database/operations/community/suggestion_operations.i

# target to preprocess a source file
database/operations/community/suggestion_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/suggestion_operations.cpp.i
.PHONY : database/operations/community/suggestion_operations.cpp.i

database/operations/community/suggestion_operations.s: database/operations/community/suggestion_operations.cpp.s
.PHONY : database/operations/community/suggestion_operations.s

# target to generate assembly for a file
database/operations/community/suggestion_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/community/suggestion_operations.cpp.s
.PHONY : database/operations/community/suggestion_operations.cpp.s

database/operations/economy/history_operations.o: database/operations/economy/history_operations.cpp.o
.PHONY : database/operations/economy/history_operations.o

# target to build an object file
database/operations/economy/history_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/history_operations.cpp.o
.PHONY : database/operations/economy/history_operations.cpp.o

database/operations/economy/history_operations.i: database/operations/economy/history_operations.cpp.i
.PHONY : database/operations/economy/history_operations.i

# target to preprocess a source file
database/operations/economy/history_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/history_operations.cpp.i
.PHONY : database/operations/economy/history_operations.cpp.i

database/operations/economy/history_operations.s: database/operations/economy/history_operations.cpp.s
.PHONY : database/operations/economy/history_operations.s

# target to generate assembly for a file
database/operations/economy/history_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/history_operations.cpp.s
.PHONY : database/operations/economy/history_operations.cpp.s

database/operations/economy/inventory_operations.o: database/operations/economy/inventory_operations.cpp.o
.PHONY : database/operations/economy/inventory_operations.o

# target to build an object file
database/operations/economy/inventory_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/inventory_operations.cpp.o
.PHONY : database/operations/economy/inventory_operations.cpp.o

database/operations/economy/inventory_operations.i: database/operations/economy/inventory_operations.cpp.i
.PHONY : database/operations/economy/inventory_operations.i

# target to preprocess a source file
database/operations/economy/inventory_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/inventory_operations.cpp.i
.PHONY : database/operations/economy/inventory_operations.cpp.i

database/operations/economy/inventory_operations.s: database/operations/economy/inventory_operations.cpp.s
.PHONY : database/operations/economy/inventory_operations.s

# target to generate assembly for a file
database/operations/economy/inventory_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/inventory_operations.cpp.s
.PHONY : database/operations/economy/inventory_operations.cpp.s

database/operations/economy/jackpot_world_events.o: database/operations/economy/jackpot_world_events.cpp.o
.PHONY : database/operations/economy/jackpot_world_events.o

# target to build an object file
database/operations/economy/jackpot_world_events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/jackpot_world_events.cpp.o
.PHONY : database/operations/economy/jackpot_world_events.cpp.o

database/operations/economy/jackpot_world_events.i: database/operations/economy/jackpot_world_events.cpp.i
.PHONY : database/operations/economy/jackpot_world_events.i

# target to preprocess a source file
database/operations/economy/jackpot_world_events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/jackpot_world_events.cpp.i
.PHONY : database/operations/economy/jackpot_world_events.cpp.i

database/operations/economy/jackpot_world_events.s: database/operations/economy/jackpot_world_events.cpp.s
.PHONY : database/operations/economy/jackpot_world_events.s

# target to generate assembly for a file
database/operations/economy/jackpot_world_events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/jackpot_world_events.cpp.s
.PHONY : database/operations/economy/jackpot_world_events.cpp.s

database/operations/economy/loan_operations.o: database/operations/economy/loan_operations.cpp.o
.PHONY : database/operations/economy/loan_operations.o

# target to build an object file
database/operations/economy/loan_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/loan_operations.cpp.o
.PHONY : database/operations/economy/loan_operations.cpp.o

database/operations/economy/loan_operations.i: database/operations/economy/loan_operations.cpp.i
.PHONY : database/operations/economy/loan_operations.i

# target to preprocess a source file
database/operations/economy/loan_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/loan_operations.cpp.i
.PHONY : database/operations/economy/loan_operations.cpp.i

database/operations/economy/loan_operations.s: database/operations/economy/loan_operations.cpp.s
.PHONY : database/operations/economy/loan_operations.s

# target to generate assembly for a file
database/operations/economy/loan_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/loan_operations.cpp.s
.PHONY : database/operations/economy/loan_operations.cpp.s

database/operations/economy/market_operations.o: database/operations/economy/market_operations.cpp.o
.PHONY : database/operations/economy/market_operations.o

# target to build an object file
database/operations/economy/market_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/market_operations.cpp.o
.PHONY : database/operations/economy/market_operations.cpp.o

database/operations/economy/market_operations.i: database/operations/economy/market_operations.cpp.i
.PHONY : database/operations/economy/market_operations.i

# target to preprocess a source file
database/operations/economy/market_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/market_operations.cpp.i
.PHONY : database/operations/economy/market_operations.cpp.i

database/operations/economy/market_operations.s: database/operations/economy/market_operations.cpp.s
.PHONY : database/operations/economy/market_operations.s

# target to generate assembly for a file
database/operations/economy/market_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/market_operations.cpp.s
.PHONY : database/operations/economy/market_operations.cpp.s

database/operations/economy/server_economy_operations.o: database/operations/economy/server_economy_operations.cpp.o
.PHONY : database/operations/economy/server_economy_operations.o

# target to build an object file
database/operations/economy/server_economy_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/server_economy_operations.cpp.o
.PHONY : database/operations/economy/server_economy_operations.cpp.o

database/operations/economy/server_economy_operations.i: database/operations/economy/server_economy_operations.cpp.i
.PHONY : database/operations/economy/server_economy_operations.i

# target to preprocess a source file
database/operations/economy/server_economy_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/server_economy_operations.cpp.i
.PHONY : database/operations/economy/server_economy_operations.cpp.i

database/operations/economy/server_economy_operations.s: database/operations/economy/server_economy_operations.cpp.s
.PHONY : database/operations/economy/server_economy_operations.s

# target to generate assembly for a file
database/operations/economy/server_economy_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/server_economy_operations.cpp.s
.PHONY : database/operations/economy/server_economy_operations.cpp.s

database/operations/economy/server_fishing_operations.o: database/operations/economy/server_fishing_operations.cpp.o
.PHONY : database/operations/economy/server_fishing_operations.o

# target to build an object file
database/operations/economy/server_fishing_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/server_fishing_operations.cpp.o
.PHONY : database/operations/economy/server_fishing_operations.cpp.o

database/operations/economy/server_fishing_operations.i: database/operations/economy/server_fishing_operations.cpp.i
.PHONY : database/operations/economy/server_fishing_operations.i

# target to preprocess a source file
database/operations/economy/server_fishing_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/server_fishing_operations.cpp.i
.PHONY : database/operations/economy/server_fishing_operations.cpp.i

database/operations/economy/server_fishing_operations.s: database/operations/economy/server_fishing_operations.cpp.s
.PHONY : database/operations/economy/server_fishing_operations.s

# target to generate assembly for a file
database/operations/economy/server_fishing_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/server_fishing_operations.cpp.s
.PHONY : database/operations/economy/server_fishing_operations.cpp.s

database/operations/economy/shop_operations.o: database/operations/economy/shop_operations.cpp.o
.PHONY : database/operations/economy/shop_operations.o

# target to build an object file
database/operations/economy/shop_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/shop_operations.cpp.o
.PHONY : database/operations/economy/shop_operations.cpp.o

database/operations/economy/shop_operations.i: database/operations/economy/shop_operations.cpp.i
.PHONY : database/operations/economy/shop_operations.i

# target to preprocess a source file
database/operations/economy/shop_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/shop_operations.cpp.i
.PHONY : database/operations/economy/shop_operations.cpp.i

database/operations/economy/shop_operations.s: database/operations/economy/shop_operations.cpp.s
.PHONY : database/operations/economy/shop_operations.s

# target to generate assembly for a file
database/operations/economy/shop_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/economy/shop_operations.cpp.s
.PHONY : database/operations/economy/shop_operations.cpp.s

database/operations/leveling/leaderboard_operations.o: database/operations/leveling/leaderboard_operations.cpp.o
.PHONY : database/operations/leveling/leaderboard_operations.o

# target to build an object file
database/operations/leveling/leaderboard_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/leaderboard_operations.cpp.o
.PHONY : database/operations/leveling/leaderboard_operations.cpp.o

database/operations/leveling/leaderboard_operations.i: database/operations/leveling/leaderboard_operations.cpp.i
.PHONY : database/operations/leveling/leaderboard_operations.i

# target to preprocess a source file
database/operations/leveling/leaderboard_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/leaderboard_operations.cpp.i
.PHONY : database/operations/leveling/leaderboard_operations.cpp.i

database/operations/leveling/leaderboard_operations.s: database/operations/leveling/leaderboard_operations.cpp.s
.PHONY : database/operations/leveling/leaderboard_operations.s

# target to generate assembly for a file
database/operations/leveling/leaderboard_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/leaderboard_operations.cpp.s
.PHONY : database/operations/leveling/leaderboard_operations.cpp.s

database/operations/leveling/leveling_operations.o: database/operations/leveling/leveling_operations.cpp.o
.PHONY : database/operations/leveling/leveling_operations.o

# target to build an object file
database/operations/leveling/leveling_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/leveling_operations.cpp.o
.PHONY : database/operations/leveling/leveling_operations.cpp.o

database/operations/leveling/leveling_operations.i: database/operations/leveling/leveling_operations.cpp.i
.PHONY : database/operations/leveling/leveling_operations.i

# target to preprocess a source file
database/operations/leveling/leveling_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/leveling_operations.cpp.i
.PHONY : database/operations/leveling/leveling_operations.cpp.i

database/operations/leveling/leveling_operations.s: database/operations/leveling/leveling_operations.cpp.s
.PHONY : database/operations/leveling/leveling_operations.s

# target to generate assembly for a file
database/operations/leveling/leveling_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/leveling_operations.cpp.s
.PHONY : database/operations/leveling/leveling_operations.cpp.s

database/operations/leveling/xp_blacklist_operations.o: database/operations/leveling/xp_blacklist_operations.cpp.o
.PHONY : database/operations/leveling/xp_blacklist_operations.o

# target to build an object file
database/operations/leveling/xp_blacklist_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/xp_blacklist_operations.cpp.o
.PHONY : database/operations/leveling/xp_blacklist_operations.cpp.o

database/operations/leveling/xp_blacklist_operations.i: database/operations/leveling/xp_blacklist_operations.cpp.i
.PHONY : database/operations/leveling/xp_blacklist_operations.i

# target to preprocess a source file
database/operations/leveling/xp_blacklist_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/xp_blacklist_operations.cpp.i
.PHONY : database/operations/leveling/xp_blacklist_operations.cpp.i

database/operations/leveling/xp_blacklist_operations.s: database/operations/leveling/xp_blacklist_operations.cpp.s
.PHONY : database/operations/leveling/xp_blacklist_operations.s

# target to generate assembly for a file
database/operations/leveling/xp_blacklist_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/leveling/xp_blacklist_operations.cpp.s
.PHONY : database/operations/leveling/xp_blacklist_operations.cpp.s

database/operations/moderation/abuse_operations.o: database/operations/moderation/abuse_operations.cpp.o
.PHONY : database/operations/moderation/abuse_operations.o

# target to build an object file
database/operations/moderation/abuse_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/abuse_operations.cpp.o
.PHONY : database/operations/moderation/abuse_operations.cpp.o

database/operations/moderation/abuse_operations.i: database/operations/moderation/abuse_operations.cpp.i
.PHONY : database/operations/moderation/abuse_operations.i

# target to preprocess a source file
database/operations/moderation/abuse_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/abuse_operations.cpp.i
.PHONY : database/operations/moderation/abuse_operations.cpp.i

database/operations/moderation/abuse_operations.s: database/operations/moderation/abuse_operations.cpp.s
.PHONY : database/operations/moderation/abuse_operations.s

# target to generate assembly for a file
database/operations/moderation/abuse_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/abuse_operations.cpp.s
.PHONY : database/operations/moderation/abuse_operations.cpp.s

database/operations/moderation/autopurge_operations.o: database/operations/moderation/autopurge_operations.cpp.o
.PHONY : database/operations/moderation/autopurge_operations.o

# target to build an object file
database/operations/moderation/autopurge_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/autopurge_operations.cpp.o
.PHONY : database/operations/moderation/autopurge_operations.cpp.o

database/operations/moderation/autopurge_operations.i: database/operations/moderation/autopurge_operations.cpp.i
.PHONY : database/operations/moderation/autopurge_operations.i

# target to preprocess a source file
database/operations/moderation/autopurge_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/autopurge_operations.cpp.i
.PHONY : database/operations/moderation/autopurge_operations.cpp.i

database/operations/moderation/autopurge_operations.s: database/operations/moderation/autopurge_operations.cpp.s
.PHONY : database/operations/moderation/autopurge_operations.s

# target to generate assembly for a file
database/operations/moderation/autopurge_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/autopurge_operations.cpp.s
.PHONY : database/operations/moderation/autopurge_operations.cpp.s

database/operations/moderation/infraction_config_operations.o: database/operations/moderation/infraction_config_operations.cpp.o
.PHONY : database/operations/moderation/infraction_config_operations.o

# target to build an object file
database/operations/moderation/infraction_config_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/infraction_config_operations.cpp.o
.PHONY : database/operations/moderation/infraction_config_operations.cpp.o

database/operations/moderation/infraction_config_operations.i: database/operations/moderation/infraction_config_operations.cpp.i
.PHONY : database/operations/moderation/infraction_config_operations.i

# target to preprocess a source file
database/operations/moderation/infraction_config_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/infraction_config_operations.cpp.i
.PHONY : database/operations/moderation/infraction_config_operations.cpp.i

database/operations/moderation/infraction_config_operations.s: database/operations/moderation/infraction_config_operations.cpp.s
.PHONY : database/operations/moderation/infraction_config_operations.s

# target to generate assembly for a file
database/operations/moderation/infraction_config_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/infraction_config_operations.cpp.s
.PHONY : database/operations/moderation/infraction_config_operations.cpp.s

database/operations/moderation/infraction_operations.o: database/operations/moderation/infraction_operations.cpp.o
.PHONY : database/operations/moderation/infraction_operations.o

# target to build an object file
database/operations/moderation/infraction_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/infraction_operations.cpp.o
.PHONY : database/operations/moderation/infraction_operations.cpp.o

database/operations/moderation/infraction_operations.i: database/operations/moderation/infraction_operations.cpp.i
.PHONY : database/operations/moderation/infraction_operations.i

# target to preprocess a source file
database/operations/moderation/infraction_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/infraction_operations.cpp.i
.PHONY : database/operations/moderation/infraction_operations.cpp.i

database/operations/moderation/infraction_operations.s: database/operations/moderation/infraction_operations.cpp.s
.PHONY : database/operations/moderation/infraction_operations.s

# target to generate assembly for a file
database/operations/moderation/infraction_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/infraction_operations.cpp.s
.PHONY : database/operations/moderation/infraction_operations.cpp.s

database/operations/moderation/permission_operations.o: database/operations/moderation/permission_operations.cpp.o
.PHONY : database/operations/moderation/permission_operations.o

# target to build an object file
database/operations/moderation/permission_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/permission_operations.cpp.o
.PHONY : database/operations/moderation/permission_operations.cpp.o

database/operations/moderation/permission_operations.i: database/operations/moderation/permission_operations.cpp.i
.PHONY : database/operations/moderation/permission_operations.i

# target to preprocess a source file
database/operations/moderation/permission_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/permission_operations.cpp.i
.PHONY : database/operations/moderation/permission_operations.cpp.i

database/operations/moderation/permission_operations.s: database/operations/moderation/permission_operations.cpp.s
.PHONY : database/operations/moderation/permission_operations.s

# target to generate assembly for a file
database/operations/moderation/permission_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/permission_operations.cpp.s
.PHONY : database/operations/moderation/permission_operations.cpp.s

database/operations/moderation/reaction_role_operations.o: database/operations/moderation/reaction_role_operations.cpp.o
.PHONY : database/operations/moderation/reaction_role_operations.o

# target to build an object file
database/operations/moderation/reaction_role_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/reaction_role_operations.cpp.o
.PHONY : database/operations/moderation/reaction_role_operations.cpp.o

database/operations/moderation/reaction_role_operations.i: database/operations/moderation/reaction_role_operations.cpp.i
.PHONY : database/operations/moderation/reaction_role_operations.i

# target to preprocess a source file
database/operations/moderation/reaction_role_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/reaction_role_operations.cpp.i
.PHONY : database/operations/moderation/reaction_role_operations.cpp.i

database/operations/moderation/reaction_role_operations.s: database/operations/moderation/reaction_role_operations.cpp.s
.PHONY : database/operations/moderation/reaction_role_operations.s

# target to generate assembly for a file
database/operations/moderation/reaction_role_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/reaction_role_operations.cpp.s
.PHONY : database/operations/moderation/reaction_role_operations.cpp.s

database/operations/moderation/role_class_operations.o: database/operations/moderation/role_class_operations.cpp.o
.PHONY : database/operations/moderation/role_class_operations.o

# target to build an object file
database/operations/moderation/role_class_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/role_class_operations.cpp.o
.PHONY : database/operations/moderation/role_class_operations.cpp.o

database/operations/moderation/role_class_operations.i: database/operations/moderation/role_class_operations.cpp.i
.PHONY : database/operations/moderation/role_class_operations.i

# target to preprocess a source file
database/operations/moderation/role_class_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/role_class_operations.cpp.i
.PHONY : database/operations/moderation/role_class_operations.cpp.i

database/operations/moderation/role_class_operations.s: database/operations/moderation/role_class_operations.cpp.s
.PHONY : database/operations/moderation/role_class_operations.s

# target to generate assembly for a file
database/operations/moderation/role_class_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/moderation/role_class_operations.cpp.s
.PHONY : database/operations/moderation/role_class_operations.cpp.s

database/operations/user/cooldown_operations.o: database/operations/user/cooldown_operations.cpp.o
.PHONY : database/operations/user/cooldown_operations.o

# target to build an object file
database/operations/user/cooldown_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/cooldown_operations.cpp.o
.PHONY : database/operations/user/cooldown_operations.cpp.o

database/operations/user/cooldown_operations.i: database/operations/user/cooldown_operations.cpp.i
.PHONY : database/operations/user/cooldown_operations.i

# target to preprocess a source file
database/operations/user/cooldown_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/cooldown_operations.cpp.i
.PHONY : database/operations/user/cooldown_operations.cpp.i

database/operations/user/cooldown_operations.s: database/operations/user/cooldown_operations.cpp.s
.PHONY : database/operations/user/cooldown_operations.s

# target to generate assembly for a file
database/operations/user/cooldown_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/cooldown_operations.cpp.s
.PHONY : database/operations/user/cooldown_operations.cpp.s

database/operations/user/prefix_operations.o: database/operations/user/prefix_operations.cpp.o
.PHONY : database/operations/user/prefix_operations.o

# target to build an object file
database/operations/user/prefix_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/prefix_operations.cpp.o
.PHONY : database/operations/user/prefix_operations.cpp.o

database/operations/user/prefix_operations.i: database/operations/user/prefix_operations.cpp.i
.PHONY : database/operations/user/prefix_operations.i

# target to preprocess a source file
database/operations/user/prefix_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/prefix_operations.cpp.i
.PHONY : database/operations/user/prefix_operations.cpp.i

database/operations/user/prefix_operations.s: database/operations/user/prefix_operations.cpp.s
.PHONY : database/operations/user/prefix_operations.s

# target to generate assembly for a file
database/operations/user/prefix_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/prefix_operations.cpp.s
.PHONY : database/operations/user/prefix_operations.cpp.s

database/operations/user/privacy_operations.o: database/operations/user/privacy_operations.cpp.o
.PHONY : database/operations/user/privacy_operations.o

# target to build an object file
database/operations/user/privacy_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/privacy_operations.cpp.o
.PHONY : database/operations/user/privacy_operations.cpp.o

database/operations/user/privacy_operations.i: database/operations/user/privacy_operations.cpp.i
.PHONY : database/operations/user/privacy_operations.i

# target to preprocess a source file
database/operations/user/privacy_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/privacy_operations.cpp.i
.PHONY : database/operations/user/privacy_operations.cpp.i

database/operations/user/privacy_operations.s: database/operations/user/privacy_operations.cpp.s
.PHONY : database/operations/user/privacy_operations.s

# target to generate assembly for a file
database/operations/user/privacy_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/privacy_operations.cpp.s
.PHONY : database/operations/user/privacy_operations.cpp.s

database/operations/user/user_operations.o: database/operations/user/user_operations.cpp.o
.PHONY : database/operations/user/user_operations.o

# target to build an object file
database/operations/user/user_operations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/user_operations.cpp.o
.PHONY : database/operations/user/user_operations.cpp.o

database/operations/user/user_operations.i: database/operations/user/user_operations.cpp.i
.PHONY : database/operations/user/user_operations.i

# target to preprocess a source file
database/operations/user/user_operations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/user_operations.cpp.i
.PHONY : database/operations/user/user_operations.cpp.i

database/operations/user/user_operations.s: database/operations/user/user_operations.cpp.s
.PHONY : database/operations/user/user_operations.s

# target to generate assembly for a file
database/operations/user/user_operations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/operations/user/user_operations.cpp.s
.PHONY : database/operations/user/user_operations.cpp.s

database/utils/database_utility.o: database/utils/database_utility.cpp.o
.PHONY : database/utils/database_utility.o

# target to build an object file
database/utils/database_utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/utils/database_utility.cpp.o
.PHONY : database/utils/database_utility.cpp.o

database/utils/database_utility.i: database/utils/database_utility.cpp.i
.PHONY : database/utils/database_utility.i

# target to preprocess a source file
database/utils/database_utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/utils/database_utility.cpp.i
.PHONY : database/utils/database_utility.cpp.i

database/utils/database_utility.s: database/utils/database_utility.cpp.s
.PHONY : database/utils/database_utility.s

# target to generate assembly for a file
database/utils/database_utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/database/utils/database_utility.cpp.s
.PHONY : database/utils/database_utility.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/main.cpp.s
.PHONY : main.cpp.s

performance/cache_manager.o: performance/cache_manager.cpp.o
.PHONY : performance/cache_manager.o

# target to build an object file
performance/cache_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/performance/cache_manager.cpp.o
.PHONY : performance/cache_manager.cpp.o

performance/cache_manager.i: performance/cache_manager.cpp.i
.PHONY : performance/cache_manager.i

# target to preprocess a source file
performance/cache_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/performance/cache_manager.cpp.i
.PHONY : performance/cache_manager.cpp.i

performance/cache_manager.s: performance/cache_manager.cpp.s
.PHONY : performance/cache_manager.s

# target to generate assembly for a file
performance/cache_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/performance/cache_manager.cpp.s
.PHONY : performance/cache_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... discord-bot"
	@echo "... commands/quiet_moderation/antispam_command.o"
	@echo "... commands/quiet_moderation/antispam_command.i"
	@echo "... commands/quiet_moderation/antispam_command.s"
	@echo "... commands/quiet_moderation/antispam_handler.o"
	@echo "... commands/quiet_moderation/antispam_handler.i"
	@echo "... commands/quiet_moderation/antispam_handler.s"
	@echo "... commands/quiet_moderation/text_filter_command.o"
	@echo "... commands/quiet_moderation/text_filter_command.i"
	@echo "... commands/quiet_moderation/text_filter_command.s"
	@echo "... commands/quiet_moderation/text_filter_handler.o"
	@echo "... commands/quiet_moderation/text_filter_handler.i"
	@echo "... commands/quiet_moderation/text_filter_handler.s"
	@echo "... database/core/connection_pool.o"
	@echo "... database/core/connection_pool.i"
	@echo "... database/core/connection_pool.s"
	@echo "... database/core/database.o"
	@echo "... database/core/database.i"
	@echo "... database/core/database.s"
	@echo "... database/operations/community/bugreport_operations.o"
	@echo "... database/operations/community/bugreport_operations.i"
	@echo "... database/operations/community/bugreport_operations.s"
	@echo "... database/operations/community/patch_operations.o"
	@echo "... database/operations/community/patch_operations.i"
	@echo "... database/operations/community/patch_operations.s"
	@echo "... database/operations/community/suggestion_operations.o"
	@echo "... database/operations/community/suggestion_operations.i"
	@echo "... database/operations/community/suggestion_operations.s"
	@echo "... database/operations/economy/history_operations.o"
	@echo "... database/operations/economy/history_operations.i"
	@echo "... database/operations/economy/history_operations.s"
	@echo "... database/operations/economy/inventory_operations.o"
	@echo "... database/operations/economy/inventory_operations.i"
	@echo "... database/operations/economy/inventory_operations.s"
	@echo "... database/operations/economy/jackpot_world_events.o"
	@echo "... database/operations/economy/jackpot_world_events.i"
	@echo "... database/operations/economy/jackpot_world_events.s"
	@echo "... database/operations/economy/loan_operations.o"
	@echo "... database/operations/economy/loan_operations.i"
	@echo "... database/operations/economy/loan_operations.s"
	@echo "... database/operations/economy/market_operations.o"
	@echo "... database/operations/economy/market_operations.i"
	@echo "... database/operations/economy/market_operations.s"
	@echo "... database/operations/economy/server_economy_operations.o"
	@echo "... database/operations/economy/server_economy_operations.i"
	@echo "... database/operations/economy/server_economy_operations.s"
	@echo "... database/operations/economy/server_fishing_operations.o"
	@echo "... database/operations/economy/server_fishing_operations.i"
	@echo "... database/operations/economy/server_fishing_operations.s"
	@echo "... database/operations/economy/shop_operations.o"
	@echo "... database/operations/economy/shop_operations.i"
	@echo "... database/operations/economy/shop_operations.s"
	@echo "... database/operations/leveling/leaderboard_operations.o"
	@echo "... database/operations/leveling/leaderboard_operations.i"
	@echo "... database/operations/leveling/leaderboard_operations.s"
	@echo "... database/operations/leveling/leveling_operations.o"
	@echo "... database/operations/leveling/leveling_operations.i"
	@echo "... database/operations/leveling/leveling_operations.s"
	@echo "... database/operations/leveling/xp_blacklist_operations.o"
	@echo "... database/operations/leveling/xp_blacklist_operations.i"
	@echo "... database/operations/leveling/xp_blacklist_operations.s"
	@echo "... database/operations/moderation/abuse_operations.o"
	@echo "... database/operations/moderation/abuse_operations.i"
	@echo "... database/operations/moderation/abuse_operations.s"
	@echo "... database/operations/moderation/autopurge_operations.o"
	@echo "... database/operations/moderation/autopurge_operations.i"
	@echo "... database/operations/moderation/autopurge_operations.s"
	@echo "... database/operations/moderation/infraction_config_operations.o"
	@echo "... database/operations/moderation/infraction_config_operations.i"
	@echo "... database/operations/moderation/infraction_config_operations.s"
	@echo "... database/operations/moderation/infraction_operations.o"
	@echo "... database/operations/moderation/infraction_operations.i"
	@echo "... database/operations/moderation/infraction_operations.s"
	@echo "... database/operations/moderation/permission_operations.o"
	@echo "... database/operations/moderation/permission_operations.i"
	@echo "... database/operations/moderation/permission_operations.s"
	@echo "... database/operations/moderation/reaction_role_operations.o"
	@echo "... database/operations/moderation/reaction_role_operations.i"
	@echo "... database/operations/moderation/reaction_role_operations.s"
	@echo "... database/operations/moderation/role_class_operations.o"
	@echo "... database/operations/moderation/role_class_operations.i"
	@echo "... database/operations/moderation/role_class_operations.s"
	@echo "... database/operations/user/cooldown_operations.o"
	@echo "... database/operations/user/cooldown_operations.i"
	@echo "... database/operations/user/cooldown_operations.s"
	@echo "... database/operations/user/prefix_operations.o"
	@echo "... database/operations/user/prefix_operations.i"
	@echo "... database/operations/user/prefix_operations.s"
	@echo "... database/operations/user/privacy_operations.o"
	@echo "... database/operations/user/privacy_operations.i"
	@echo "... database/operations/user/privacy_operations.s"
	@echo "... database/operations/user/user_operations.o"
	@echo "... database/operations/user/user_operations.i"
	@echo "... database/operations/user/user_operations.s"
	@echo "... database/utils/database_utility.o"
	@echo "... database/utils/database_utility.i"
	@echo "... database/utils/database_utility.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... performance/cache_manager.o"
	@echo "... performance/cache_manager.i"
	@echo "... performance/cache_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

