#pragma once
#include <dpp/dpp.h>

// Helper to send an embed to a guild channel using a webhook owned by this bot when possible.
// The webhook is NOT persisted — the channel ID is stored and we look up/create the webhook each time.
// Fallback: if webhook operations fail we send normally with message_create.

namespace commands {
namespace quiet_moderation {

// keep a record of webhook IDs that we have created/used so cleanup can recognise
// messages generated by them.  using an `inline` variable avoids linker issues.
inline std::set<dpp::snowflake> owned_webhooks;

inline void send_embed_via_webhook(dpp::cluster& bot, dpp::snowflake channel_id, const dpp::embed& embed) {
    if (channel_id == 0) return;

    // Try to find an existing webhook in the channel that belongs to this bot.
    bot.get_channel_webhooks(channel_id, [channel_id, &bot, embed](const dpp::confirmation_callback_t& cb) {
        if (cb.is_error()) {
            // Fallback to normal send
            bot.message_create(dpp::message(channel_id, embed));
            return;
        }

        auto whmap = cb.get<dpp::webhook_map>();
        dpp::webhook chosen_wh;
        bool found = false;
        for (auto &p : whmap) {
            const dpp::webhook &w = p.second;
            if (w.user_obj.id == bot.me.id) { chosen_wh = w; found = true; 
                // remember this webhook for the cleanup command
                owned_webhooks.insert(w.id);
                break; }
        }

        auto do_fallback = [&](void) {
            bot.message_create(dpp::message(channel_id, embed));
        };

        dpp::message m;
        m.add_embed(embed);

        if (found) {
            // Execute the existing webhook (fire-and-forget)
            bot.execute_webhook(chosen_wh, m, false, 0, "", [channel_id, &bot, do_fallback](const dpp::confirmation_callback_t& exec_cb) {
                if (exec_cb.is_error()) {
                    do_fallback();
                }
            });
            return;
        }

        // No existing webhook owned by us — create one and use it immediately (we do NOT persist it)
        dpp::webhook newwh;
        newwh.channel_id = channel_id;
        newwh.name = ::std::string("bpp-logger-") + ::std::to_string(bot.me.id);

        bot.create_webhook(newwh, [channel_id, &bot, m, do_fallback](const dpp::confirmation_callback_t& create_cb) {
            if (create_cb.is_error()) {
                do_fallback();
                return;
            }
            dpp::webhook created = create_cb.get<dpp::webhook>();
            // remember our new webhook id for future cleanup
            owned_webhooks.insert(created.id);
            bot.execute_webhook(created, m, false, 0, "", [channel_id, &bot, do_fallback](const dpp::confirmation_callback_t& exec_cb) {
                if (exec_cb.is_error()) do_fallback();
            });
        });
    });
}

} // namespace quiet_moderation
} // namespace commands
